apiVersion: v1
kind: ServiceAccount
metadata:
  name: hirelink-ksa
  namespace: hirelink-prod
  annotations:
    iam.gke.io/gcp-service-account: sa-hirelink-workload-prod@deadbots.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hirelink-web-ksa
  namespace: hirelink-prod
