apiVersion: v1
kind: ConfigMap
metadata:
  name: hirelink-config
  namespace: hirelink-prod
data:
  DJANGO_DEBUG_PROD: "false"
  DJANGO_ALLOWED_HOSTS_PROD: "app.niranjan.cloud,api.niranjan.cloud,admin.niranjan.cloud,localhost,127.0.0.1"
  CORS_ALLOWED_ORIGINS_PROD: "https://app.niranjan.cloud,https://api.niranjan.cloud,https://admin.niranjan.cloud,http://localhost:3000,http://127.0.0.1:3000"
  CSRF_TRUSTED_ORIGINS_PROD: "https://app.niranjan.cloud,https://api.niranjan.cloud,https://admin.niranjan.cloud,http://localhost:3000,http://127.0.0.1:3000"
  NEXT_PUBLIC_API_URL: "https://api.niranjan.cloud"
