# Generated by Django 5.2 on 2025-06-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_resume_rejection_reason_alter_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='directapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True),
        ),
        migrations.AlterField(
            model_name='directapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_made', 'Offer Made'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by Candidate'), ('on_hold', 'On Hold'), ('hired', 'Hired'), ('pending', 'Pending')], default='applied', max_length=20),
        ),
    ]
