apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - servicemonitor.yaml
  - prometheus-rules.yaml
  - otel-collector.yaml
  - loki-ruler-configmap.yaml
