apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hirelink-api
  namespace: observability
  labels:
    release: kube-prom-stack
spec:
  namespaceSelector:
    matchNames: ["hirelink-prod"]
  selector:
    matchLabels:
      app: hirelink-api
  endpoints:
    - port: http
      path: /health/
      interval: 30s
      scrapeTimeout: 10s

