apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hirelink-gcp-secrets
  namespace: hirelink-prod
spec:
  provider: gcp
  secretObjects:
    - secretName: hirelink-secret-env
      type: Opaque
      data:
        - objectName: DJANGO_SECRET_KEY_PROD
          key: DJANGO_SECRET_KEY_PROD
        - objectName: DB_USER_PROD
          key: DB_USER_PROD
        - objectName: DB_PASSWORD_PROD
          key: DB_PASSWORD_PROD
        - objectName: DB_HOST_PROD
          key: DB_HOST_PROD
        - objectName: DB_PORT_PROD
          key: DB_PORT_PROD
        - objectName: DB_NAME_PROD
          key: DB_NAME_PROD
        - objectName: DB_SSLMODE_PROD
          key: DB_SSLMODE_PROD
        - objectName: CLOUD_SQL_CONNECTION_NAME_PROD
          key: CLOUD_SQL_CONNECTION_NAME_PROD
        - objectName: USE_CLOUD_SQL_PROXY_PROD
          key: USE_CLOUD_SQL_PROXY_PROD
        - objectName: EMAIL_HOST_PASSWORD_PROD
          key: EMAIL_HOST_PASSWORD_PROD
        - objectName: GOOGLE_CLIENT_ID_PROD
          key: GOOGLE_CLIENT_ID_PROD
        - objectName: GOOGLE_CLIENT_SECRET_PROD
          key: GOOGLE_CLIENT_SECRET_PROD
        - objectName: RAZORPAY_KEY_ID_PROD
          key: RAZORPAY_KEY_ID_PROD
        - objectName: RAZORPAY_KEY_SECRET_PROD
          key: RAZORPAY_KEY_SECRET_PROD
        - objectName: RAZORPAY_WEBHOOK_SECRET_PROD
          key: RAZORPAY_WEBHOOK_SECRET_PROD
        - objectName: GCS_CREDENTIALS_JSON_PROD
          key: GCS_CREDENTIALS_JSON_PROD
  parameters:
    secrets: |
      - resourceName: "projects/deadbots/secrets/DJANGO_SECRET_KEY_PROD/versions/latest"
        path: "DJANGO_SECRET_KEY_PROD"
      - resourceName: "projects/deadbots/secrets/DB_USER_PROD/versions/latest"
        path: "DB_USER_PROD"
      - resourceName: "projects/deadbots/secrets/DB_PASSWORD_PROD/versions/latest"
        path: "DB_PASSWORD_PROD"
      - resourceName: "projects/deadbots/secrets/DB_HOST_PROD/versions/latest"
        path: "DB_HOST_PROD"
      - resourceName: "projects/deadbots/secrets/DB_PORT_PROD/versions/latest"
        path: "DB_PORT_PROD"
      - resourceName: "projects/deadbots/secrets/DB_NAME_PROD/versions/latest"
        path: "DB_NAME_PROD"
      - resourceName: "projects/deadbots/secrets/DB_SSLMODE_PROD/versions/latest"
        path: "DB_SSLMODE_PROD"
      - resourceName: "projects/deadbots/secrets/CLOUD_SQL_CONNECTION_NAME_PROD/versions/latest"
        path: "CLOUD_SQL_CONNECTION_NAME_PROD"
      - resourceName: "projects/deadbots/secrets/USE_CLOUD_SQL_PROXY_PROD/versions/latest"
        path: "USE_CLOUD_SQL_PROXY_PROD"
      - resourceName: "projects/deadbots/secrets/EMAIL_HOST_PASSWORD_PROD/versions/latest"
        path: "EMAIL_HOST_PASSWORD_PROD"
      - resourceName: "projects/deadbots/secrets/GOOGLE_CLIENT_ID_PROD/versions/latest"
        path: "GOOGLE_CLIENT_ID_PROD"
      - resourceName: "projects/deadbots/secrets/GOOGLE_CLIENT_SECRET_PROD/versions/latest"
        path: "GOOGLE_CLIENT_SECRET_PROD"
      - resourceName: "projects/deadbots/secrets/RAZORPAY_KEY_ID_PROD/versions/latest"
        path: "RAZORPAY_KEY_ID_PROD"
      - resourceName: "projects/deadbots/secrets/RAZORPAY_KEY_SECRET_PROD/versions/latest"
        path: "RAZORPAY_KEY_SECRET_PROD"
      - resourceName: "projects/deadbots/secrets/RAZORPAY_WEBHOOK_SECRET_PROD/versions/latest"
        path: "RAZORPAY_WEBHOOK_SECRET_PROD"
      - resourceName: "projects/deadbots/secrets/GCS_CREDENTIALS_JSON/versions/latest"
        path: "GCS_CREDENTIALS_JSON_PROD"

